
const keys = {
  'Backquote': ['§', '±', '>', '<'],
  'Digit1': [1, '!', '1', '!'],
  'Digit2': [2, '@', '2', '"'],
  'Digit3': [3, '#', '3', '№'],
  'Digit4': [4, '$', '4', '%'],
  'Digit5': [5, '%', '5', ':'],
  'Digit6': [6, '^', '6', ','],
  'Digit7': [7, '&', '7', '.'],
  'Digit8': [8, '*', '8', ';'],
  'Digit9': [9, '(', '9', '('],
  'Digit0': [0, ')', '0', ')'],
  'Minus': ['-', '_', '-', '_'],
  'Equal': ['=', '+', '=', '+'],
  'Backspace': ['', '', '', ''],
  'Tab': ['    ', '    ', '    ', '    '],
  'KeyQ': ['q', 'Q', 'й', 'Й'],
  'KeyW': ['w', 'W', 'ц', 'Ц'],
  'KeyE': ['e', 'E', 'у', 'У'],
  'KeyR': ['r', 'R', 'к', 'К'],
  'KeyT': ['t', 'T', 'е', 'Е'],
  'KeyY': ['y', 'Y', 'н', 'Н'],
  'KeyU': ['u', 'U', 'г', 'Г'],
  'KeyI': ['i', 'I', 'ш', 'Ш'],
  'KeyO': ['o', 'O', 'щ', 'Щ'],
  'KeyP': ['p', 'P', 'з', 'З'],
  'BracketLeft': ['[', '{', 'х', 'Х'],
  'BracketRight': [']', '}', 'ъ', 'Ъ'],
  'Backslash': ['\\', '|', 'ё', 'Ё'],
  'CapsLock': ['', '', '', ''], 
  'KeyA': ['a', 'A', 'ф', 'Ф'],
  'KeyS': ['s', 'S', 'ы', 'Ы'],
  'KeyD': ['d', 'D', 'в', 'В'],
  'KeyF': ['f', 'F', 'а', 'А'],
  'KeyG': ['g', 'G', 'п', 'П'],
  'KeyH': ['h', 'H', 'р', 'Р'],
  'KeyJ': ['j', 'J', 'о', 'О'],
  'KeyK': ['k', 'K', 'л', 'Л'],
  'KeyL': ['l', 'L', 'д', 'Д'],
  'Semicolon': [';', ':', 'ж', 'Ж'],
  'Quote': ['\'', '"', 'э', 'Э'],
  'Enter': ['\n', '\n', '\n', '\n'],
  'ShiftLeft': ['', '', '', ''],
  'IntlBackslash': ['`', '~', ']', '['],
  'KeyZ': ['z', 'Z', 'я', 'Я'],
  'KeyX': ['x', 'X', 'ч', 'Ч'],
  'KeyC': ['c', 'C', 'с', 'С'],
  'KeyV': ['v', 'V', 'м', 'М'],
  'KeyB': ['b', 'B', 'и', 'И'],
  'KeyN': ['n', 'N', 'т', 'Т'],
  'KeyM': ['m', 'M', 'ь', 'Ь'],
  'Comma': [',', '<', 'б', 'Б'],
  'Period': ['.', '>', 'ю', 'Ю'],
  'Slash': ['/', '?', '/', '?'],
  'ShiftRight': ['', '', '', ''],
  'ControlLeft': ['control', 'control', 'control', 'control'],
  'AltLeft': ['', '', '', ''],
  'MetaLeft': ['command', 'command', 'command', 'command'],
  'Space': [' ', ' ', ' ', ' '],
  'MetaRight': ['command', 'command', 'command', 'command'],
  'AltRight': ['option', 'option', 'option', 'option'],
  'ArrowLeft': ['left', 'left', 'left', 'left'],
  'ArrowUp': ['up', 'up', 'up', 'up'],
  'ArrowDown': ['down', 'down', 'down', 'up'],
  'ArrowRight': ['right', 'right', 'right', 'up']
}

export default keys